### ISSUE TITLE
Join forces?

### ISSUE THREAD

**Issue by pogopaule** [jakedouglas/climatejobs#7]
Hey @jakedouglas!

I just stumbled across your project. Good job!

I created a [similar list](https://github.com/pogopaule/awesome-sustainability-jobs) and was wondering if it makes sense to join forces? Any ideas?

Since my first language is German I have been mainly focusing on jobs in German speaking countries. Maybe I could contribute the non-German companies to your list and reference your project in mine?

Cheers

**Comment by jakedouglas** [comment]
Hey! I'm not actively maintaining this anymore, given that other more dedicated efforts like https://climatebase.org have come about. Happy to accept a PR though if you want this list to link to yours.

**Comment by pogopaule** [comment]
Ok!
